//parking store
//find park store
POST http://localhost:80/findstore HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTUwMDQ5MDEsImV4cCI6MTU5NTAxMjEwMX0.-XSvj0TP6stzIoe31cHcHTjqvqc9wefSowMhbsrlUS4

{
    "idparkstore":6
}
###



//create parking area
POST http://localhost:80/parking/area HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTI5MjQ4MjUsImV4cCI6MTU5MjkzMjAyNX0.nwj_UJCusPgdM6F6-mZGtiIJORFF0GsrZ6uWsfgpnEM

{
    "nomeparcheggio":"CiccioPanzo",
    "coordinate": "13.550911,43.406311",
    "comune": "Recanati"
}
###
//update parking area
PUT http://localhost:80/parking/area/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTE4MDI5NzcsImV4cCI6MTU5MTgxMDE3N30.utH8JFmusKLIaVpUia3JnnvT96SkgRrKpvMbbnaEPug

{
   "nomeparcheggio":"Cavour",
    "coordinate": "13.550914,43.406316",
    "comune": "Recanati"
}
###
//get all area
GET http://localhost:80/parkingarea HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTE4MDI5NzcsImV4cCI6MTU5MTgxMDE3N30.utH8JFmusKLIaVpUia3JnnvT96SkgRrKpvMbbnaEPug
###
//get area by id
GET http://localhost:80/parking/area/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTE4MDI5NzcsImV4cCI6MTU5MTgxMDE3N30.utH8JFmusKLIaVpUia3JnnvT96SkgRrKpvMbbnaEPug
###
//remove area
DELETE http://localhost:80/parking/area/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTE4MDI5NzcsImV4cCI6MTU5MTgxMDE3N30.utH8JFmusKLIaVpUia3JnnvT96SkgRrKpvMbbnaEPug
###
//delete all park
DELETE http://localhost:80/parkingarea HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTE4MDI5NzcsImV4cCI6MTU5MTgxMDE3N30.utH8JFmusKLIaVpUia3JnnvT96SkgRrKpvMbbnaEPug
###

//--------------parking slot---------------------------------------------
//create park

POST http://localhost:80/parking HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTQ2NjA2NDcsImV4cCI6MTU5NDY2Nzg0N30.RHWsEQClHZsJx3C1XgWhdgq8RHnp-bhVW0ochfCEwTE

{
    "status": 1,
    "coord": "43.39904,13.55244",
    "comune": "PROVA",
    "costoorario": 1.6
}
###

//home
GET http://localhost:80/ HTTP/1.1
###
//update park
PUT http://localhost:80/parking/10 HTTP/1.1
content-type: application/json

{
    "status": 0,
    "coord": [13.075009882450104,43.13747491759089],
    "comune": "montecassiano",
    "costoorario": 6.3
}
###

//remove park
DELETE http://localhost:80/parking/133 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTQ2NjA2NDcsImV4cCI6MTU5NDY2Nzg0N30.RHWsEQClHZsJx3C1XgWhdgq8RHnp-bhVW0ochfCEwTE
###

//get all park
GET http://localhost:80/parking HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

//get park by id
GET http://localhost:80/parking/206 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbUBnbWFpbC5pdCIsImRyaXZlcklkIjozMzYsImFkbWluIjpmYWxzZSwiaWF0IjoxNTg5MTkyNzgwLCJleHAiOjE1ODkxOTYzODB9.w6B4m_QJMzj6Tm53FAqIbJvLzqk7WR6iCHGrQ6MQ-rE
###

//delete all park
DELETE http://localhost:80/parking HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

//get nearest by id
GET http://localhost:80/parkingnearest/13.552525,43.398551/pippo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTQ5MTI3OTQsImV4cCI6MTU5NDkxOTk5NH0.p5y-mOPNDYinDB-EOaMhYOJ0IFUtu7XGT-hZznPYcdM
###

//parking sensor trigger
GET http://localhost:80/parking/parked/parkedslot HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTQ5MTI3OTQsImV4cCI6MTU5NDkxOTk5NH0.p5y-mOPNDYinDB-EOaMhYOJ0IFUtu7XGT-hZznPYcdM
###

//park occupied
GET http://localhost:80/parking/parked/parkoccupied HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbUBnbWFpbC5pdCIsImRyaXZlcklkIjozMzYsImFkbWluIjpmYWxzZSwiaWF0IjoxNTg5NDY0NjA0LCJleHAiOjE1ODk0NzE4MDR9.Dn6fsEkmfBztNijZCHu7Q8ltfreZkyiZhVtVxsy4mCg
###
//park malfuntion
GET http://localhost:80/parking/parked/malfunction HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbUBnbWFpbC5pdCIsImRyaXZlcklkIjozMzYsImFkbWluIjpmYWxzZSwiaWF0IjoxNTg5NDY0NjA0LCJleHAiOjE1ODk0NzE4MDR9.Dn6fsEkmfBztNijZCHu7Q8ltfreZkyiZhVtVxsy4mCg
###
//notification for municipality police simulating parking sensor by id
GET http://localhost:80/parking/notification/206 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbUBnbWFpbC5pdCIsImRyaXZlcklkIjozMzYsImFkbWluIjpmYWxzZSwiaWF0IjoxNTg5MzYzMTA5LCJleHAiOjE1ODkzNjY3MDl9.c98m-L-pVcacYk1pyf6I352rz4kT11n58RG5KZ0gZW0
###

//get cancellation
GET http://localhost:80/parkingnearest/cancellation/cancel/13.552461,43.398963 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbUBnbWFpbC5pdCIsImRyaXZlcklkIjozMzYsImFkbWluIjpmYWxzZSwiaWF0IjoxNTkxMDkxMDM3LCJleHAiOjE1OTEwOTgyMzd9.0ug1s-SAWT5RGvkb2O_e8SkVDHE5ICfdyh46imf7qD0
###

//DRIVER EXAMPLE

//driver registration
POST http://localhost:80/register HTTP/1.1
content-type: application/json

{
    "username": "willi",
    "email": "willi@gmail.it",
    "password": "samuele",
    "targa": "ED106JG"
}
###

//LOGIN GUZZO

POST http://localhost:80/login HTTP/1.1
content-type: application/json

{
    "username": "Willy",
    "email": "sam@gmail.it",
    "password": "morichetta"
}
###

//login WILLI

POST http://localhost:80/login HTTP/1.1
content-type: application/json

{
    "username": "willi",
    "email": "willi@gmail.it",
    "password": "samuele"
    }
###

POST http://localhost:80/users/update/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM0NiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODk5MDc5MjMsImV4cCI6MTU4OTkxNTEyM30.U457a_lTtTk73M4zKIbZ1PRd021U44cxpaI0m5ILaXQ

{
    "username": "willi",
    "email": "willi@gmail.it"
}
###

//add targa
POST http://localhost:80/users/add/addtarga HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTE4ODc0NjYsImV4cCI6MTU5MTg5NDY2Nn0.Gw4h5XeRmu5RPN3rE3x0UoN5IorlIeWVrbT1MkPdDAM

{
    "targa": "EF220GR"
}
###

//delete targa
POST http://localhost:80/users/delete/deletetarga HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGxpQGdtYWlsLml0IiwiZHJpdmVySWQiOjM1NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1OTA1NzUxNDEsImV4cCI6MTU5MDU4MjM0MX0.tqbsNbiQ-n_NHQZuBotgZNV8pUfvC6nSoAZMzPxCtQ4

{
    "targa": ""
}
###

//get driver by email
GET http://localhost:80/users/find/find HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbUBnbWFpbC5pdCIsImRyaXZlcklkIjozMzYsImFkbWluIjpmYWxzZSwiaWF0IjoxNTkwNTAxNjIzLCJleHAiOjE1OTA1MDg4MjN9.pomdmwHmSQ3ficeA9DHzP0t3_gLXHbI-hVP0i_BzOi8
###


//get all drivers
GET http://localhost:80/users HTTP/1.1
###
//get driver by id
GET http://localhost:80/users/44 HTTP/1.1
###
//delete all drivers
DELETE http://localhost:80/users HTTP/1.1
###
//remove driver account logged with id from the token
DELETE http://localhost:80/usersid HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

POST http://localhost:80/users/44/report HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODE1MjA2MjgsImV4cCI6MTU4MTUyMTgyOH0.7vIo2gl1pkWeh4wT99mWHRIdGCnTDhQ_nhs6LpJAG1A

{   "subject": "email di prova",
    "text": "test email"
}
###