

//create park
POST http://localhost:80/parking HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODE5NDg2MjEsImV4cCI6MTU4MTk0OTgyMX0.NalbP7rI7OFod91tU8PfRKSYSqchs2OvL72pTKQ2gkI

{
    "status": 0,
    "coord": "13.073208,43.140010",
    "comune": "montecassiano",
    "costoorario": 6.3
}
###
//home
GET http://localhost:80/ HTTP/1.1
###
//update park
PUT http://localhost:80/parking/10 HTTP/1.1
content-type: application/json

{
    "status": 0,
    "coord": [13.075009882450104,43.13747491759089],
    "comune": "montecassiano",
    "costoorario": 6.3
}
###

//remove park
DELETE http://localhost:80/parking/133 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

//get all park
GET http://localhost:80/parking HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

//get park by id
GET http://localhost:80/parking/26 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

//delete all park
DELETE http://localhost:80/parking HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

//get nearest by id
GET http://localhost:80/parkingnearest/13.06775,43.14247 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODI4MDE2MjIsImV4cCI6MTU4MjgwMjgyMn0.2pBFr1rwmO1EeurwMhoQqjV3ht6ICq3WWWqlURAVJzM
###


//notification for municipality police simulating parking sensor by id
GET http://localhost:80/parking/notification/126 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

//get cancellation
GET http://localhost:80/parkingnearest/cancellation/13.066519,43.139471 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODI4MDE2MjIsImV4cCI6MTU4MjgwMjgyMn0.2pBFr1rwmO1EeurwMhoQqjV3ht6ICq3WWWqlURAVJzM
###

//DRIVER EXAMPLE

//driver registration
POST http://localhost:80/register HTTP/1.1
content-type: application/json

{
    "username": "Guzzo",
    "email": "sam@gmail.it",
    "password": "samuele"
}
###

POST http://localhost:80/login HTTP/1.1
content-type: application/json

{
    "username": "Guzzo",
    "email": "sam@gmail.it",
    "password": "samuele"
}
###

//get all drivers
GET http://localhost:80/users HTTP/1.1
###
//get driver by id
GET http://localhost:80/users/44 HTTP/1.1
###
//delete all drivers
DELETE http://localhost:80/users HTTP/1.1
###
//remove driver account logged with id from the token
DELETE http://localhost:80/usersid HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODIyMDU0MDEsImV4cCI6MTU4MjIwNjYwMX0.AplICz-EEoZB5cwXKSH_a1WF8jHb-2ouUm6kAdqYSXQ
###

POST http://localhost:80/users/44/report HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbSIsImRyaXZlcklkIjo0NCwiYWRtaW4iOmZhbHNlLCJpYXQiOjE1ODE1MjA2MjgsImV4cCI6MTU4MTUyMTgyOH0.7vIo2gl1pkWeh4wT99mWHRIdGCnTDhQ_nhs6LpJAG1A

{   "subject": "email di prova",
    "text": "test email"
}
###